AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  MyPassword:
    Type: String
    NoEcho: true  # <-- This hides the value in outputs/logs
Resources:
  MySecretPassed:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-secretsmanager-secret-generatesecretstring.html
      SecretString: !Ref MyPassword


# Hides the parameter value in:
# AWS CloudFormation console outputs
# AWS CLI responses (describe-stacks)
# CloudTrail logs
# Replaces the actual value with ***** (asterisks) in logs/UIs.
# This prevent sensitive information exposure