AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  InlineLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler  # Corrected: Only the function name is needed for inline code
      Runtime: python3.12
      InlineCode: |
        import json
        from faker import Faker
        def handler(event, context):
            fake = Faker()
            message = 'Hello {}!'.format(fake.name())  
            info = {
                "Type": "Container Example",
                "Version": 1
            }
            info_json = json.dumps(info)
            print(info_json)
            return { 
                'message' : message
            }
      Layers:
        - arn:aws:lambda:eu-west-3:783764602222:layer:my-layer-name:2