AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ASGArn:
    Type: String
    Default: arn:aws:autoscaling:eu-west-3:783764602222:autoScalingGroup:58bd1c0c-468c-4890-a5df-df85e59aee4f:autoScalingGroupName/ecs-ec2-basic-ASG-XgMDV8UQBj4u
  ClusterStack:
    Type: String
    Default: ecs-ec2-basic
Resources:
  MyCapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
        Name: MyCPECSBasic
        AutoScalingGroupProvider:
          AutoScalingGroupArn: !Ref ASGArn
          ManagedScaling:
              MaximumScalingStepSize: 3
              MinimumScalingStepSize: 1
              Status: ENABLED
              TargetCapacity: 100
          ManagedTerminationProtection: DISABLED 
  ClusterCPAssociation:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-clustercapacityproviderassociations.html
    Type: "AWS::ECS::ClusterCapacityProviderAssociations"
    Properties:
      Cluster:
        Fn::ImportValue:
          !Sub "${ClusterStack}ClusterName"
      CapacityProviders:
        - !Ref MyCapacityProvider
      DefaultCapacityProviderStrategy:
        - Base: 0
          Weight: 1
          CapacityProvider: !Ref MyCapacityProvider 